CREATE TABLE status (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    disk TEXT NOT NULL,
    path TEXT NOT NULL,
    dir_gb DOUBLE NOT NULL,
    avail_gb DOUBLE NOT NULL,
    total_gb DOUBLE NOT NULL,
    n_files INTEGER NOT NULL
)
